### ISSUE TITLE
Invitation system html and  css

### ISSUE THREAD

**Issue by Ulaize** [ekaitzht/murnow#194]
NOTE: All pop-ups but the one called New Beta Landing page should have an X mark on the top right of the pop up. By clicking this X button, it should take the user to the murnow beta landing page. If this is too much work, please leave it until we have the call.

All pop ups will follow a similar structure so please apply the general changes based on the first section I am about to write (new beta landing page)
# New Beta Landing page

![login page](https://cloud.githubusercontent.com/assets/13457207/10955775/472d36b2-8324-11e5-8385-871d51b4abfd.png)

``` css
/*I wanted to give some padding to the pop up*/
md-dialog.md-transition-in {
    opacity: 1;
    padding: 3em;
}
```

Here is a mock up of the HTML (that you can obviously change) so you can understand where I am getting at with the css.

``` html
<h1>Makeup Reivews Now</h1>
<h3>The Makeup Review Haven</h3>
<p>Makeup Reviews Now is now only available for those who got invitations from us. If you have already registered, you can now log in. You can request an invitation by clicking <a href="">here</a>.</p><!-- please link here to the request invitation pop up -->

<!-- forgot password link here -->
<div>
  <!-- the form goes here -->
</div>

<!-- request invitation here -->
```

``` css
h1{
    margin: 0px;
    font-size: 5em;
    margin-top: 1rem;
    color: rgb(255,170,187);
    font-family: Amatic SC;
    text-align: center;
}

h3{
/*This font here should be the same as h2 in the front page (except for the color). I have looked at the mixin you have used for the home page but I would prefer if you changed that mixin for the below css*/
    font-family: 'Josefin Sans', sans-serif;
    font-weight: 300;
    text-align: center;
    font-size: 1.5em;
    color: rgb(255,170,187);
    margin: .7em;
}

p{
/*This is the usual body font. You probably have a mixin for the body font. I took it from other pages*/
    opacity: 0.54;
    color: black;
    font-size: 18px;
    line-height: 21px;
    margin: 0rem;
    font-family: "Lucida Grande";
    font-weight: 400;
    text-align: center;
}

```

I hate 'h2' in all the pop-ups! In all of the pop ups we have a header 'h2' and the font size is too large on desktop but ok on mobile. This is because you have used rem. If you use em, this is resolved. Please apply the right em to all the headers of the pop-ups (for this sprint and also all others)>

``` css
h2{
    font-size: 2em !important;
    text-align: center; /*no funciona ni siquiera con !important en dev tools.*/
}
```

Aqui tienes un articulo sobre la diferencia entre rem y em: https://j.eremy.net/confused-about-rem-and-em/

---

Then there is a div with the form. I want it to have more space on the sides so it looks more like the example above. Here is how I have achieved it.

``` css
div{
    margin-left: auto;
    margin-right: auto;
    min-width: 50%;
}
```

Finally, for the links "forgotten password" and request invitation", I want it to be in `text-form:capitalize`. Please apply this CSS to ALL pop ups that have this class. I believe these are spans with a class `ng-scope`.

Please apply the usual css for buttons.

The background overlay, you can find in Dropbox>murnow>sprints>1.invitation sprint.
# Invitation page

Very similar to previous one but some elements are gone and the text in the `p` tag changes.

![request invitation page](https://cloud.githubusercontent.com/assets/13457207/10955980/b0eca366-8325-11e5-949b-60f86ad38b51.png)

``` html
<h1>Makeup Reivews Now</h1>
<h3>The Makeup Review Haven</h3>
<p>Please provide us with your email and name and we will reach out with an invitation as soon as these are available. -->
<div>
  <!-- the form goes here -->
</div>
```

Please change the text of the `p` tag.
# Thank you page

This is what it currently looks like:

<img width="824" alt="screen shot 2015-11-04 at 6 57 03 pm" src="https://cloud.githubusercontent.com/assets/13457207/10956061/5f4106b4-8326-11e5-8109-33b1c1d3d29a.png">

The ideal is a hybrid of the previous pages and the current one:

![thank you](https://cloud.githubusercontent.com/assets/13457207/10956038/29e2f7b6-8326-11e5-81d3-59fa6598a600.png)

``` html
<h1>Makeup Reivews Now</h1>
<h3>The Makeup Review Haven</h3>
<div>
  <!-- the form goes here with the content just like it is now-->
</div>

<p>Thank you. We will be in touch very soon!</p>
```
# Reset password

Currently this is what it looks like:

<img width="1023" alt="screen shot 2015-11-04 at 7 01 59 pm" src="https://cloud.githubusercontent.com/assets/13457207/10956083/9738084c-8326-11e5-8546-132ea35ed884.png">

I only need you to change the background overlay (to the cute one) and the text. The hint text should say "Email" and the button should say "Recover my password"
# Invitation page

![invitation page](https://cloud.githubusercontent.com/assets/13457207/10956129/21e39542-8327-11e5-8ab3-cb22b76a879b.png)

Exact same view as the Invitation Page but different content.

``` html
<h1>Makeup Reivews Now</h1>
<h3>The Makeup Review Haven</h3>
<p>Please provide us with your email and name and we will reach out with an invitation as soon as these are available. -->
<div>
  <!-- the form goes here -->
</div>
```

`p` tag content: You have been invited to Murnow! Make Up Reviews Now allows you to voice your opinion on your favourite makeup and see what other people are saying. Sign up now to get a preview of what is in store!

The button should say: JOIN
# Invitation already used

![invitation invalid](https://cloud.githubusercontent.com/assets/13457207/10956283/6244c0c4-8328-11e5-86f5-9deb3807c2cb.png)

This will be the same as the invitation page but you can add a `p` tag that says "This invitation has already been used. You can request a new invitation here."

The here should be underline and link you to the request invitation page.
